### PR TITLE
added first draft for previewing widget thumbnails

### PR DESCRIPTION
**Pull request by thenewcoder**
I added a preview window above the drop down list with thumbnails of the widgets. I also added icons next to the names in the drop down list. Both can be used to choose a widget. I left both in as I'm not sure which you'd prefer. I also didn't mess with the scale of the preview window, unless you decide to accept this commit and make a design decision.

The thumbnails I included are just placeholders and should be replaced with better ones. I also didn't include a default icon for when the user adds his own widget shape. It's a first draft that can be changed and tweaked.

### CODE REVIEW

**Comment by waylow** [comment]
Oh hey @thenewcoder - I didn't see this until now......oh my.  Sorry for the delay.

I'll take a look at this really soon.  Thank you for your interest :)

**Comment by waylow** [comment]
Dude I love this - sorry it has taken me so long to get to it


I have a question though.
How are the widget images made?
Just thinking if it's possible for users to add their own, or have a few placeholders for user added widgets.

But this is flipping great man.  Thank you.

**Comment by thenewcoder** [comment]
It's been so long I barely remember without looking it up...

The way I created the widget images were by converting the widget to a curve,
and then adding a small amount of depth or extrude to it to make it more visible for the camera.

Then adding a camera directly above it, world background light strength turned up to about 60
to get the white color, and finally with transparent turned on I rendered it out. (Eevee)

Not necessarily the way to go, but I was testing to see if perhaps it could be automated. I quickly
found out that it doesn't work well for some shapes. Would need to manually tweak either the extrude
or depth to avoid any wonkiness.

But perhaps there is a way to get it to work, as I do think the best way would be to do something automated
similar to the asset browser thumbnails, unless it would be a rarely used feature with too much effort to implement.

Another idea could be to let the user position a camera etc over the widget and then press "render" within
the add-on itself and an image would be saved.

Or perhaps, less desirable!?, user prepares everything and then just "uploads/saves" the image. More freedom but also
more effort. And would anyone want to go through the hoops!?

Maybe could offer a couple of options on how to save a widget image. But either way, a few placeholders for user
added widgets would probably be needed as I'm sure many people wouldn't want to bother with creating their own.

Thank you for liking and merging!

**Comment by waylow** [comment]
The asset browser thing was something I was thinking about too.
But it could render it from the camera vantage point when you pressed the button (and did all the other stuff like material etc behind the scenes)
I have asked someone at work about different ideas to see what it worth the effort, and what is outside the scope this add-on.

I also disconnected my fork from the original project - mainly because I was sick of github telling my that I was 2 commits behind and 128 commits ahead. haha
This 'new' project is still in the same address but it unfortunately detached your pull request information as well.  So even though I've merged your code into the develop branch - you aren't (yet) on the records as a contributor.
I will figure out how to fix that.

Also you wouldn't happen to be the Markus Berg who is a member at cgcookie would you?

**Comment by thenewcoder** [comment]
Good idea to get someone else's opinion! There are already so many widgets included that would most likely cover most use cases, but there is always that one person that wants/needs more. But let's wait and see on the feedback.

Yup, I'm that Markus Berg! I was wondering how long it would take for you to figure it out. :) But I'm sorry for disappearing for such a long time. My wife's dad passed away last year and I ended up burning myself out trying to juggle everything, and I just didn't have the same motivation anymore. On a positive note, I just started watching your new Rigging course, so hopefully that can reignite the passion again. Be on the lookout for new exercise submissions in the hopefully not too distant future.

And don't worry about me not showing up as a contributor. Besides almost losing my mind trying to remember which widget was called what and saving my own sanity by adding images, I just wanted to try to give something back for all the help.

**Pull request merged**
